package projectoosd;
import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.JOptionPane;


public class PurchaseOfficer extends javax.swing.JFrame {

      
    public PurchaseOfficer() {
        initComponents();
    }
    

    
    public void RequestQuotation(String StaffReqID ,String Count, String Medicine , String Description, String Type , String Categories , String Quantity ){
       int result = Integer.parseInt(Quantity) * 3;
       Count = String.valueOf(Integer.parseInt(Count) + 1);

        try
            {
                 String FILENAME = "OrderRequest.txt";
         
                 BufferedWriter bw = null;
                 FileWriter fw = null;
             
                 String s = StaffReqID + ";" + Count + ";"+ Medicine + ";" + Description + ";"+ Type + ";" + Categories +  ";" + Quantity + ";" + result +"\n";
                 fw = new FileWriter(FILENAME,true);
                 bw = new BufferedWriter(fw);
                 bw.write(s);
                 bw.close();
                 
                 JOptionPane.showMessageDialog(null, "Addition Completed!", "The order has been requested!", JOptionPane.INFORMATION_MESSAGE);

            }
             catch(Exception e)
            {
                 JOptionPane.showMessageDialog(null, "Invalid Order Details", "error", JOptionPane.ERROR_MESSAGE);
            }        
    
    }
    
    public void PlaceOrder(String id ,String Count, String MedicineName, String MedicineDescription , String Type , String Categories , String Quantity, String Status  ){
        Count = String.valueOf(Integer.parseInt(Count) + 1);
        Status = "Delivered" ;
        try
            {
                 String FILENAME = "PlaceOrder.txt";
         
                 BufferedWriter bw = null;
                 FileWriter fw = null;

                 String s = id + ";" + Count + ";" + MedicineName + ";" + MedicineDescription + ";" + Type + ";" + Categories +  ";" + Quantity + ";" + Status +"\n";
                 fw = new FileWriter(FILENAME,true);
                 bw = new BufferedWriter(fw);
                 bw.write(s);
                 bw.close();
                 
                 JOptionPane.showConfirmDialog(null,"Click Yes to confirm the order", "Verify Order", JOptionPane.YES_NO_OPTION);
                 JOptionPane.showMessageDialog(null, "The order has been send!", "Order Completed!", JOptionPane.INFORMATION_MESSAGE);
                 
            }
             catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        JButtonNext = new javax.swing.JButton();
        JButtonLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Purchase Officer");
        setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Welcome ! ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eclipse Demo", 0, 18), new java.awt.Color(28, 83, 215))); // NOI18N

        jLabel1.setFont(new java.awt.Font("The Next Font", 0, 12)); // NOI18N
        jLabel1.setText("Choose  Your Categories :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Request Quotation", "Order Request", "Approve Order", "Place Order", "Order Status", "Update Stock" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        JButtonNext.setText("Next");
        JButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonNextActionPerformed(evt);
            }
        });

        JButtonLogOut.setText("Log Out");
        JButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonNextActionPerformed
        String a = (String)jComboBox1.getSelectedItem();
        
       if(a.contains("Request Quotation"))
       {
           //RequestOrder Info = new RequestOrder();
          // Info.setVisible(true);
          // dispose();
       }
       if(a.contains("Order Request"))
       {
           //O//rderRequest Info = new OrderRequest ();
          // Info.setVisible(true);
          //dispose();
       }
       if(a.contains("Approve Order"))
       {
        /// /  ApproveOrder Info = new ApproveOrder();
         //  Info.setVisible(true);
        // dispose();
       }
       if(a.contains("Place Order"))
       {
        //PlaceOrder Info = new PlaceOrder ();
     //  Info.setVisible(true);
     //     dispose();
       }
       if(a.contains("Order Status"))
       {
          // OrderStatus Info = new OrderStatus ();
         //  Info.setVisible(true);
          //dispose();
       }
       if(a.contains("Update Stock"))
       {
           //PlaceOrder Info = new PlaceOrder ();
          // Info.setVisible(true);
        // dispose();
       }
                                 
    }//GEN-LAST:event_JButtonNextActionPerformed

    private void JButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonLogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JButtonLogOutActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseOfficer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseOfficer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseOfficer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseOfficer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchaseOfficer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonLogOut;
    private javax.swing.JButton JButtonNext;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
